---
title: "Case Study 09"
author: Jeongwon Lee
date: August 1, 2020
output: github_document
---

## Impart libraries

```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
data(world)
data(us_states)
```

## Download data

```{r}
# Download a csv from noaa with storm track information
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

storm_data <- read_csv(dataurl)
```

## Wrangle the data

```{r}
# convert ISO time
storm_data_2 <-storm_data
storm_data_2$YEAR <-lubridate::year(storm_data$ISO_TIME)

# select storm in 1950~2024
storm_data_2 <- storm_data_2 %>% filter(YEAR >= 1950 & YEAR <= 2024)

# mutate -999 to NA
storm_data_2 <- storm_data_2 %>% mutate_if(is.numeric, function(x) ifelse(x==-999.0, NA, x))

# mutate DECADE column
storm_data_2 <- storm_data_2 %>% mutate(DECADE=(floor(YEAR/10)*10))

# convert lan and lon columns to sf object
storm_data_2 <- storm_data_2[2:nrow(storm_data_2),]
storm_data_sf <- storm_data_2 %>% st_as_sf(coords=c("LON","LAT"),crs=4326)

# set region boundary box
region <- st_bbox(storm_data_sf) 
```

## Make the first plot

```{r}
# visualize the plot
ggplot() +
  geom_sf(data = world) +
  stat_bin2d(data=storm_data_sf, aes(y=st_coordinates(storm_data_sf)[,2], x=st_coordinates(storm_data_sf)[,1]),bins=100) +
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000)) +
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)]) +
  facet_wrap(~DECADE) +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank())

```

## Create table

```{r}
us_states_transformed <- st_transform(us_states, st_crs(storm_data_sf)) %>% select(state = NAME)

storm_states <- st_join(storm_data_sf, us_states_transformed, join = st_intersects,left = F) %>%
  group_by(state) %>% 
  summarize(storms=length(unique(NAME))) %>% 
  arrange(desc(storms)) %>% 
  slice(1:5)

storm_states

```
